### PR TITLE
[Chore] Add solr json loader as submodule into index-bioentities repo

### PR DESCRIPTION
**Pull request by ke4**
Changes:
- Added solr-jsonl-loader as a submodule
- Replaced solr-jsonl-chunk-loader.sh with a symlink that point to the similarly named file in the previously added submodule. That file in the submodule is going to be shared across other repositories, too.

### CODE REVIEW

**Comment by anilthanki** [comment]
Does this symlink perform same as actual file with all relative paths and bash commands like `dirname` etc

**Comment by ke4** [comment]
@anilthanki We extracted that single json chunk loader file into a separate repo. We are going to include that repo as a submodule in these repos:
- index-bioentities
- index-scxa
- solr-bulk
- maybe in index-gxa??? later

**Comment by anilthanki** [comment]
> @anilthanki We extracted that single json chunk loader file into a separate repo. We are going to include that repo as a submodule in these repos:
> 
> * index-bioentities
> * index-scxa
> * solr-bulk
> * maybe in index-gxa??? later

I totally agree we should not be maintaining multiple copies of same script, what I was asking is if its symlinked then certain relative functions (i.e. `dirname`) will behave same as actual file or do we need to change them?

**Review by alfonsomunozpomer — COMMENTED** [review]
All good!

**Review by alfonsomunozpomer — APPROVED** [review]
All good!

**Review by anilthanki — APPROVED** [review]
LGTM

**Review by pmb59 — APPROVED** [review]
LGTM!

My only comment is regarding this commit [ec053f4](https://github.com/ebi-gene-expression-group/index-bioentities/pull/13/commits/ec053f427d02b4f0f712d0934b6bec902618cc6a). There, you are redefining and exporting, and already defined `$SOLR_HOST` variable. Why is this necessary only for this test and not for the other tests in `tests/bioentities.bats`?

**Comment by ke4** [comment]
> LGTM!
> 
> My only comment is regarding this commit [ec053f4](https://github.com/ebi-gene-expression-group/index-bioentities/pull/13/commits/ec053f427d02b4f0f712d0934b6bec902618cc6a). There, you are redefining and exporting, and already defined `$SOLR_HOST` variable. Why is this necessary only for this test and not for the other tests in `tests/bioentities.bats`?

@alfonsomunozpomer did that fix. As far as I remember without that fix the test wanted to connect to solr on localhost. That modification fixed that test. None of the other tests needed that change.

**Pull request merged**
